version: '3'
services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/ibrahho/code
    ports:
      - "8888:8888"
    command: start.sh jupyter notebook --NotebookApp.token='' --NotebookApp.disable_check_xsrf=true --NotebookApp.allow_origin='*' --NotebookApp.ip='0.0.0.0'
