version: '3.8'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: Welcome4$
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: test@domain.local
      PGADMIN_DEFAULT_PASSWORD: test1234
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
