version: '3.8'
services:
  pyspark-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - /Users/hossamtabana/downloads/data:/data
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
